# this config was migrated from renv.lock on 2026-10-09
[project]
name = "hopi"
r_version = "4.6.1"

repositories = [
  { alias = "P3M", url = "https://packagemanager.posit.co/cran/latest" },
  { alias = "CRAN", url = "https://cloud.r-project.org/" },
]

dependencies = [
  { name = "ISOweek", repository = "P3M" },
  { name = "R6", repository = "P3M" },
  { name = "RColorBrewer", repository = "P3M" },
  { name = "S7", repository = "P3M" },
  { name = "askpass", repository = "P3M" },
  { name = "bit", repository = "P3M" },
  { name = "bit64", repository = "CRAN" },
  { name = "bizdays", repository = "P3M" },
  { name = "cli", repository = "P3M" },
  { name = "clipr", repository = "P3M" },
  { name = "cpp11", repository = "P3M" },
  { name = "crayon", repository = "P3M" },
  { name = "dplyr", repository = "P3M" },
  { name = "farver", repository = "P3M" },
  { name = "fs", repository = "P3M" },
  { name = "generics", repository = "P3M" },
  { name = "ggplot2", repository = "P3M" },
  { name = "glue", repository = "P3M" },
  { name = "gtable", repository = "P3M" },
  { name = "hms", repository = "P3M" },
  { name = "isoband", repository = "P3M" },
  { name = "jsonlite", repository = "P3M" },
  { name = "labeling", repository = "P3M" },
  { name = "lifecycle", repository = "P3M" },
  { name = "lubridate", repository = "P3M" },
  { name = "magrittr", repository = "P3M" },
  { name = "mime", repository = "P3M" },
  { name = "openssl", repository = "P3M" },
  { name = "pillar", repository = "P3M" },
  { name = "pkgconfig", repository = "P3M" },
  { name = "prettyunits", repository = "P3M" },
  { name = "progress", repository = "P3M" },
  { name = "purrr", repository = "P3M" },
  { name = "readr", repository = "P3M" },
  { name = "rlang", repository = "P3M" },
  { name = "scales", repository = "P3M" },
  { name = "stringi", repository = "P3M" },
  { name = "stringr", repository = "P3M" },
  { name = "sys", repository = "P3M" },
  { name = "tibble", repository = "P3M" },
  { name = "tidyr", repository = "P3M" },
  { name = "tidyselect", repository = "P3M" },
  { name = "timechange", repository = "P3M" },
  { name = "tzdb", repository = "P3M" },
  { name = "uklr", git = "https://github.com/kvasilopoulos/uklr", commit = "80a64e92da7f7e32fef41b9ad038721d3b38d2d4" },
  { name = "utf8", repository = "P3M" },
  { name = "vctrs", repository = "P3M" },
  { name = "viridisLite", repository = "P3M" },
  { name = "vroom", repository = "P3M" },
  { name = "withr", repository = "P3M" },
  "data.table",
  "Matrix",
  "zoo",
  "itsmr",
  "knitr",
  "rmarkdown",
    "devtools",
    "roxygen2",
    "testthat",
]
