---
title: "update"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{update}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = FALSE
)
```


## Update

1. Clone the repo

```{r clone, eval=FALSE}
library(gert)
gert::git_clone("https://github.com/lancs-macro/hopi.git")
```

2. Load & Update 

```{r update, eval=FALSE}
devtools::load_all(".")
options(timeout = 15*60)

td <- process_data(end_date = next_release_to_date())
gc()

```

```{r update2, eval=FALSE}
# To update all frequencies
update(td)

# Or alternatively
update_monthly(td)
update_quarterly(td)
update_annual(td)

```

3. Git push

```{r push, eval=FALSE}

git_add(".")
git_commit("Commit msg")
git_push()
```


<!--
# Preprocess --------------------------------------------------------------

# download_lr_file()
# tidy_lr_file()

# nuts1_weekly <- rsindex(td, freq = "weekly")
# nuts1_daily <- rsindex(td, freq = "daily")

# cleanup()
-->

